### Offerlist normal
GET http://localhost:4000/api/offers/offersList?itemsPerPage=100&page=1&active=true

### returnOfferId
GET http://localhost:4000/api/offers/returnOfferId/37305

### OfferKeys
GET http://localhost:4000/api/offers/offerKeys/2506423 

### Offerlist com loop p descobrir jogos impossíveis
GET http://localhost:4000/api/offers/offersList?ids=74797,78621,26374

###
POST http://localhost:4000/api/offers/createOffer
Content-Type: application/json

{
    "product": "",
    "wholesale_mode": "0",
    "seller_price": 15,
    "tier_one_seller_price": "",
    "tier_two_seller_price": "",
    "status": 1,
    "keys": 3,
    "is_preorder": false
}

### searchOfferById productId = 45746
GET http://localhost:4000/api/offers/search/2783132

### O productId é "inútil" para editar
PUT http://localhost:4000/api/offers/editOffer
Content-Type: application/json

{
    "productId": 1767, 
    "menorPreco": 0.54,
    "offerId": 2783132
}