### Offerlist normal
GET http://localhost:4000/g2a/api/offers/offersList?itemsPerPage=100&page=1&active=true

### Offerlist com loop
GET http://localhost:4000/g2a/api/offers/returnOffersData

### searchOfferById productId = 45746
GET http://localhost:4000/g2a/api/offers/searchOfferById/350a9b55-b73a-409c-b75e-6bc60372ebea
# Content-Type: application/json

# {
#     "offerId": "be02b0cc-f203-43a7-a5ef-ad49acde4164"
# }

### O productId é "inútil" para editar
PATCH http://localhost:4000/g2a/api/offers/editOffer/
Content-Type: application/json

{
    "productId": "10000176345001",
    "menorPreco": "6.5",
    "offerId": "a0445116-c5cd-4596-9aff-64156b891409",
    "offerType": "game",
    "offerSize": 1,
    "gameName": "Mercury Race Steam Key GLOBAL"
}