#
POST http://localhost:4000/g2a/api/products/compareById
Content-Type: application/json

{
    "productId": "10000036960002",
    "offerId": "91d9950f-a84a-496b-8987-710c5815a372",
    "offerType": "TESTE",
    "offerSize": 1,
    "gameName": "TESTE"
}

###
GET http://localhost:4000/g2a/api/products/priceResearcher/10000036960002