#
POST http://localhost:4000/api/products/compareById
Content-Type: application/json

{
   "productId": "10000008826005",
    "menorPreco": "3.03",
    "offerId": "60320a3e-a111-48ed-acf1-d17328031d06",
    "offerType": "game",
    "offerSize": 2,
    "gameName": "The Addams Family: Mansion Mayhem (PC) - Steam Key - GLOBAL"
}